name: "CI for Demo App"

on: [push]

jobs:
    build_code:
        runs-on: ubuntu_latest
        steps:
            - name: Code checkout
              uses: actions/checkout@4
            - name: Run some commands
              run: |
                ls -l
