name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Dev

    steps:
    - uses: actions/checkout@v4
    - name: Install docker 
      uses: docker/setup-buildx-action@v3.12.0
    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_HUB_SECRET}}
    - name: Docker Push
      uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/demo:${{github.run_id}}
  write-to-repo:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.CI_CD_DEMO_REPO_READ_WRITE}}
      - name: Change Image in k8s manifest file
        run: |
          sed -i "s|image: .*|image: ${{secrets.DOCKER_USERNAME}}/demo:${{github.run_id}}|" k8s/manifest.yaml
      - name: Commit changes to Repo
        run: |
          git config --global user.email "ganeshbabualeti@gmail.com"
          git config --global user.name "GaneshAleti"
          git add k8s/manifest.yaml
          git commit -m "[CI]: Update Demo image tag"
          git push origin main
